### ISSUE TITLE
Galapagotchi needs a logo?

### ISSUE THREAD

**Issue by diegochavez** [elastic-interval/pretenst#37]
Hey Guys, I'm glad you keep going this small project, I'm wondering if I can start to contribute, well if you are open we can start with some representative logo? Let's invite more creative guys! @elvisfurcic 😃 I think is easy to develop a UI with a defined logo style.

**Comment by geralddejong** [comment]
Yes!  I'm hoping that @elvisfurcic will share his creativity soon, since he'll be free in a week.  He's a web audio afficionado, so I'm hoping that Galapagotchi will soon make sound!
