### ISSUE TITLE
Let's add a React UI framework?

### ISSUE THREAD

**Issue by diegochavez** [elastic-interval/pretenst#38]
Since the main goal is to give a good user experience, with a little effort I suggest to use https://material-ui.com/ is a react based version, what do you think guys? @elvisfurcic @geralddejong I've used in a few projects and it's really nice to create a theme and extends.

**Comment by geralddejong** [comment]
There is currently an obstacle to making the best result with React, and that is the dependency on ` "react-three": "^0.9.7"`.  I have not yet been able to escape this issue so that the latest version of React can be used. I would really appreciate advice/help for that.

**Comment by diegochavez** [comment]
Ok I see, probably would be good to explore implementing another three react renderer or go bare bone use React only for Web UI, Looks like we can start migrating to Create React App latest version then see how much is broken :D, I saw the dependency is probably not too big on this lib, is about updating libs and see how far I can get 👍 . look the files affected by that lib https://github.com/beautiful-code-bv/galapagotchi/search?q=from+%22react-three%22&unscoped_q=from+%22react-three%22
